### ISSUE TITLE
StepStick driver considerations

### ISSUE THREAD

**Issue by ArkadiuszRaj** [ghent360/PrntrBoardV2#12]
Did another small thing, found inside PR #11 

![obraz](https://user-images.githubusercontent.com/16072469/104857437-e4f0b700-5918-11eb-8361-4aae8917e7dd.png)

Questions:
- shall DIAG output of the stepstick (TMC one) be connected to Alarm1?
- what is purpose of CFG1-3 pins on the PCI slot? i.e PrntrBoard do not use them.
- what is the purpose of this small eeprom on drive board?

**Comment by ArkadiuszRaj** [comment]
I saw your schematic changes and as I have some spare time I have played a bit with routing.

![obraz](https://user-images.githubusercontent.com/16072469/104887433-8bfe3e80-596b-11eb-8972-81922dff6d34.png)

![obraz](https://user-images.githubusercontent.com/16072469/104887480-9e787800-596b-11eb-8939-042b40e2b652.png)

4 layers, one used to distribute V_IO.

That is preliminary view. I have added more vias around cap ground.

**Comment by ghent360** [comment]
I added one more jumper and routed it in 2 layers. May need some more vias
for the GND. Add your handle to the Copyright, it is mostly your design.

**Comment by ArkadiuszRaj** [comment]
PR #13 ready

**Comment by ghent360** [comment]
Merged.
