### ISSUE TITLE
when trying to open pcb file it says date of kicad version required is newer after 19 jan 2020

### ISSUE THREAD

**Issue by svalambhia** [ghent360/PrntrBoardV2#2]
I am using kicad 5.1.8 nov 2020 but still when open pcb file i got error   kicad version required is newer after 19 jan 2020. schematic works fine. I remember I had open pcb file in older kicad version. 
i tried to download new files for github and tried to open it ... it gives same error. do I need to go back to old version ?

**Comment by ghent360** [comment]
I’m using KiCad 6 nightly builds.

**Comment by svalambhia** [comment]
Oh ok
