### ISSUE TITLE
WiFi Addon

### ISSUE THREAD

**Issue by ArkadiuszRaj** [ghent360/PrntrBoardV2#6]
PR already provided #7 

ESP-12F used, to allow usage of DWC. Connected to main board via SPI2 exposed on EXT1/2 ports
Local USB to easly update firmware of the ESP.
As EXT1/2 do not provide 3V3 I have put also local dc-dcconverter.

![obraz](https://user-images.githubusercontent.com/16072469/104820231-c795ed00-5833-11eb-945d-639146497d73.png)

![obraz](https://user-images.githubusercontent.com/16072469/104820220-b4831d00-5833-11eb-8f00-3cd768a9d4e0.png)

**Comment by ArkadiuszRaj** [comment]
If stacking for legacy LCD would be needed I suggest to use long leg 5x2 version of header sockets.

**Comment by ArkadiuszRaj** [comment]
Correction to Header placement and spacing applied. Sorry for missing checking such a basic stuff

**Comment by ArkadiuszRaj** [comment]
Regarding RST - it is essential and shall be connected. 

My bad I have not checked the EXP ports.

**Comment by ghent360** [comment]
Well, not your fault. I just noticed it by chance when trying to see if the
connector of the addon lines up with the connector on the board. Again
thank you for the effort.

**Comment by ghent360** [comment]
I think this PR is done and we can close it. We can fix the EXP2.4 pin in the main board schematics as separate issue.
