### ISSUE TITLE
Folders structure enhancement

### ISSUE THREAD

**Issue by ArkadiuszRaj** [ghent360/PrntrBoardV2#8]
I suggest to add following folder structure
- (one folder per product)

  - Manufacture

    - schematics.pdf
    - ibom.html
    - gerbers.zip
    - bom.csv
    - placement.csv

This is complete data for the ordering boards as well as assembly. Such a product manufacture' subfolder then represents "release" data content. If you agree I can start with making order following this suggestion.

**Comment by ghent360** [comment]
The "Manufacture" folder sounds like a great idea. Since there are multiple
boards in this depot, we have to decide how to proceed:
Option 1) have board prefix: prntrboard_v2_schematics.pdf,
prntrboard_v2_ibom.htmletc for the main board; then tmc2209_schematics.pdf
tmc2209_ibom.html etc.
Option 2) have subfolders: Manufacture\prntrboardv2; Manufacture\tmc2209
etc.

I personally favor #2 since with #1 the list of files would be quite large
and hard to manage what is what, but I'm open to other suggestions.

~V

**Comment by ArkadiuszRaj** [comment]
Option #2 follows my idea.

I will refactor files but will not add jlcpcb assembly files. Have no idea
how you create those and frankly speaking it is painful process as they do
not follow any standard of initial orientation. Thus every project one must
check if components orientation is OK.

W dniu niedz., 17.01.2021 o 17:02 ghent360 <notifications@github.com>
napisał(a):

> The "Manufacture" folder sounds like a great idea. Since there are multiple
> boards in this depot, we have to decide how to proceed:
> Option 1) have board prefix: prntrboard_v2_schematics.pdf,
> prntrboard_v2_ibom.htmletc for the main board; then tmc2209_schematics.pdf
> tmc2209_ibom.html etc.
> Option 2) have subfolders: Manufacture\prntrboardv2; Manufacture\tmc2209
> etc.
>
> I personally favor #2 since with #1 the list of files would be quite large
> and hard to manage what is what, but I'm open to other suggestions.
>
> ~V
>

**Comment by ghent360** [comment]
I have a magic awk script that fixes the orientation on components I know
are wrong. JLC people are nice and will fix wrong orientation for you even
if you get it wrong, just have some cues in the silkscreen about the
correct orientation.

**Comment by ghent360** [comment]
Yes I agree one has to check the orientation. Ill add the manufacture files
I have used and know to work well.

**Comment by ArkadiuszRaj** [comment]
PR pushed, now the ball is yours 👍 

What I am thinking about is that new version of for example TMC2209 driver shall not appear as additional file set but the repository shall by flagged with tags. Then information about revision in README file shall be updated keeping old data untouched.

**Comment by ghent360** [comment]
I changed the StepStick driver schematics a bit. Removed the external voltage source - I'm not aware of any drivers that can be driven with over 24V successfully. Added local filter cap and a few jumpers to account for a variety of BTT and other drivers.

**Comment by ghent360** [comment]
I updated all the driver boards.
